import "./globals.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import Navbar from "./_components/Navbar";
import { useForm } from 'react-hook-form'
import { Toaster } from 'react-hot-toast';
import Footer from "./_components/Footer";
import { AppProvider } from "@/context/AppContext";

config.autoAddCss = false;


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
      <AppProvider>
        <Navbar />
        {children}
        <Footer />
        <Toaster />
        </AppProvider>


      </body>
    </html>
  );
}
